export const siteConfig = {
  siteUrl: "https://changhong-shinelong.vercel.app",
  brandName: "Chanhong ShineLong",
  legalNameEn: "Changzhou Changhong Xianglong Machinery Technology Co., Ltd.",
  legalNameZh: "常州市常宏祥隆机械科技有限公司",
  legalNameStatus: "derived_direct_translation" as const,
  foundedYear: 2010,
  phone: "13961228745",
  email: "1390339757@qq.com",
  addressZh: "常州市武进区牛塘镇大通西路197号2-101",
  addressEn: "No. 2-101, Datong West Road, Niutang Town, Wujin District, Changzhou City, Jiangsu, China",
  domesticSite: "http://www.chxljx.com/",
  siteAreaSqm: 6000,
  monthlyCapacityUnits: 500,
  leadTimeWorkingDays: 40,
  moqUnits: 1,
  facilityAreas: [
    { name: "Machining", description: "Precision machining of rotor, housing and shaft components." },
    { name: "Grinding & Welding", description: "Surface grinding and structural welding of valve bodies." },
    { name: "Assembly", description: "Rotor, bearing, seal and drive assembly into finished units." },
    { name: "Inspection", description: "Dimensional and functional inspection prior to staging." },
    { name: "Warehouse", description: "Finished and semi-finished unit staging and dispatch." },
  ],
  materials: ["Cast iron", "Carbon steel", "Stainless steel"],
  extendedMaterials: ["Nylon lining", "Ceramic lining", "Titanium-alloy variants"],
  industries: [
    "Grain",
    "Food",
    "Feed",
    "Chemical",
    "Petrochemical",
    "Pharmaceutical",
    "Drying",
    "Environmental protection",
    "Dust collection",
    "New energy (including lithium battery)",
  ],
} as const

export const navigation = [
  { label: "Home", href: "/" },
  { label: "Products", href: "/products" },
  { label: "Applications", href: "/applications" },
  { label: "Manufacturing", href: "/manufacturing" },
  { label: "About", href: "/about" },
  { label: "Insights", href: "/news" },
  { label: "Contact", href: "/contact" },
] as const
